#pragma once

#include "stdafx.h"

#define FLAG_ALLYFACTION	FLAG_06
#define FLAG_ENEMYFACTION	FLAG_05
#define FLAG_UNIT			FLAG_07
#define FLAG_CAMERAOB		FLAG_08
#define FLAG_RIDE			FLAG_04
#define FLAG_NPC			FLAG_02
#define FLAG_EVENT			FLAG_01

#define FLAG_ITEM		(FLAG_03 | FLAG_04)
#define FLAG_PLAYER		(FLAG_UNIT | FLAG_ALLYFACTION | FLAG_CAMERAOB | FLAG_RIDE | FLAG_ITEM | FLAG_NPC | FLAG_EVENT)
#define FLAG_PBULLET	(FLAG_ENEMYFACTION)
#define FLAG_ENEMY		(FLAG_UNIT | FLAG_ENEMYFACTION | FLAG_RIDE)
#define FLAG_VEHICLE	(FLAG_UNIT | FLAG_ENEMYFACTION)
#define FLAG_EBULLET	(FLAG_ALLYFACTION)
